### PR TITLE
Expose options.unescape flag to skip special char escaping

### PR DESCRIPTION
**Pull request by loopiezlol**
Todo:
- [ ] handle special case for AST BLOCKQUOTE compilation

### CODE REVIEW

**Comment by lizTheDeveloper** [comment]
hey we should probably try to get this into remark-stringify so that we can continue to use that OSS dep- otherwise we'll get into the same issues that our main app ended up in where we're pointing to specific commits of personal forks of OSS

**Comment by nem035** [comment]
We did discuss it with them briefly (@Loopiezlol did) but they weren't leaning towards doing it.

**Comment by lizTheDeveloper** [comment]
laaaame

**Comment by Loopiezlol** [comment]
@lizTheDeveloper @nem035 
Left them one more message on gitter:

screen shot 2018-06-14 at 11 36 01

fingers crossed

**Pull request merged**
